/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sources;

/**
 *
 * @author alumno
 */
public class JFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxContinente = new javax.swing.JComboBox<>();
        jComboBoxPais = new javax.swing.JComboBox<>();
        jButtonBuscar = new javax.swing.JButton();
        jLabelTexto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBoxContinente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asia", "America", "Africa", "Europa", "Oceania" }));
        jComboBoxContinente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxContinenteActionPerformed(evt);
            }
        });

        jComboBoxPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Continent" }));
        jComboBoxPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPaisActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Search");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(jButtonBuscar)
                .addContainerGap(343, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxContinente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxPais, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBoxContinente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(18, Short.MAX_VALUE)
                        .addComponent(jComboBoxPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addComponent(jLabelTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButtonBuscar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxContinenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxContinenteActionPerformed
        if(jComboBoxContinente.getSelectedItem().equals("Asia")){
            jComboBoxPais.removeAllItems();
           String paises[]=new String[]{"Japan","China","Russia","South Korea","India"};
            for(int i=0;i<paises.length;i++){
                jComboBoxPais.addItem(paises[i]);    
            } 
        }
        if(jComboBoxContinente.getSelectedItem().equals("America")){
           jComboBoxPais.removeAllItems();
            String paises[]=new String[]{"Mexico","USA","Canada","Brazil","Chile"};
            for(int i=0;i<paises.length;i++){
                jComboBoxPais.addItem(paises[i]);    
            } 
        }
        if(jComboBoxContinente.getSelectedItem().equals("Europa")){
           jComboBoxPais.removeAllItems();
            String paises[]=new String[]{"Germany","Belgium","Croatia","Portugal","Spain"};
            for(int i=0;i<paises.length;i++){
                jComboBoxPais.addItem(paises[i]);    
            } 
        }
        if(jComboBoxContinente.getSelectedItem().equals("Africa")){
           jComboBoxPais.removeAllItems();
            String paises[]=new String[]{"Angola","Cameroon","Congo","South Africa","Egypt"};
            for(int i=0;i<paises.length;i++){
                jComboBoxPais.addItem(paises[i]);    
            } 
        }
        if(jComboBoxContinente.getSelectedItem().equals("Oceania")){
           jComboBoxPais.removeAllItems();
            String paises[]=new String[]{"New Zealand","Australia","Samoa","Nauru","Fiji"};
            for(int i=0;i<paises.length;i++){
                jComboBoxPais.addItem(paises[i]);    
            } 
        }
        
        
        
    }//GEN-LAST:event_jComboBoxContinenteActionPerformed

    private void jComboBoxPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPaisActionPerformed
        
    }//GEN-LAST:event_jComboBoxPaisActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
       String pais=jComboBoxPais.getItemAt(jComboBoxPais.getSelectedIndex());
       String continente=jComboBoxContinente.getItemAt(jComboBoxContinente.getSelectedIndex());
       String capitalesAsia[]=new String[]{"Tokyo","Beijing","Moscow","Seoul","New","Deli"};
       String capitalesAmerica[]=new String[]{"CDMX","Washington D.C.","Ottawa","Brasilia","Santiago"};
       String capitalesEuropa[]=new String[]{"Berlin","Brussels","Zagreb","Lisbon","Madrid"};
       String capitalesAfrica[]=new String[]{"Luanda","Yaounde","Kinshasa","Pretoria","Cairo"};
       String capitalesOceania[]=new String[]{"Wellington","Canberra","Apia","Yaren","Suva"};
       if(continente.equals("Asia")){
           String capital=capitalesAsia[jComboBoxPais.getSelectedIndex()];
           jLabelTexto.setText("Continent: "+continente+"Country: "+pais+"Capital: "+capital);
       }
       if(continente.equals("Africa")){
           String capital=capitalesAfrica[jComboBoxPais.getSelectedIndex()];
           jLabelTexto.setText("Continent: "+continente+"Country: "+pais+"Capital: "+capital);
       }
       if(continente.equals("America")){
           String capital=capitalesAmerica[jComboBoxPais.getSelectedIndex()];
           jLabelTexto.setText("Continent: "+continente+"Country: "+pais+"Capital: "+capital);
       }
       if(continente.equals("Oceania")){
           String capital=capitalesOceania[jComboBoxPais.getSelectedIndex()];
           jLabelTexto.setText("Continent: "+continente+"Country: "+pais+"Capital: "+capital);
       }
       if(continente.equals("Europa")){
           String capital=capitalesEuropa[jComboBoxPais.getSelectedIndex()];
           jLabelTexto.setText("Continent: "+continente+"Country: "+pais+"Capital: "+capital);
       }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JComboBox<String> jComboBoxContinente;
    private javax.swing.JComboBox<String> jComboBoxPais;
    private javax.swing.JLabel jLabelTexto;
    // End of variables declaration//GEN-END:variables
}
